---

- hosts: tag_dazone_True
  user: ubuntu
  tasks:
    - name: simple disk bandwidth probe
      command: hdparm -Tt /dev/md0
      register: hdparm
      become: true
    - debug: var=hdparm.stdout_lines

    - block:
      - name: purge
        shell: sync && echo 3 > /proc/sys/vm/drop_caches
        become: true
      - name: query2
        shell: ./target/release/query2 -i buren-snz -k {{ item[0] }} -r {{ item[1] }} | tee -a ~/output
        register: query
        args:
          chdir: dazone
      - debug: var=query.stdout_lines
      with_nested:
        - [ "hashes", "timely" ]
        - [ 8, 10, 12 ]
