---

- hosts: tag_dazone_True
  user: ubuntu
  tasks:
    - name: simple disk bandwidth probe
      shell: hdparm -Tt /dev/md0
      become: true
      register: hdparm
    - debug: var=hdparm.stdout_lines

    - name: query2
      shell: |
        sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"
        ./target/release/query2 -i buren-snz -r {{ item[0] }} -k {{ item[1] }} >> ~/output
      args:
        chdir: dazone
      with_nested:
        - [ "hashes", "timely" ]
        - [ 8, 10, 12 ]
      register: query2
    - debug: var=query2
