---

- hosts: tag_dazone_True
  user: ubuntu
  tasks:
    - name: simple disk bandwidth probe
      shell: hdparm -Tt /dev/md0
      become: true
      register: hdparm
    - debug: var=hdparm.stdout_lines

    - name: delete output
      command: rm -f output
    - name: query2
      shell: |
        sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"
        ./target/release/query2 -i buren-snz -r {{ item.r }} -k {{ item.k }}  -b {{ item.b }} -w {{ item.w }} >> ~/output
      args:
        chdir: dazone
      with_items:
        - { r: 'hashes', k:  8, b: 257, w: "{{ 2*ansible_processor_cores }}"   }
        - { r: 'hashes', k: 10, b: 257, w: "{{ 2*ansible_processor_cores }}"   }
        - { r: 'hashes', k: 12, b: 307, w: "{{ 2*ansible_processor_cores }}"   }
        - { r: 'timely', k:  8, b:   0, w: "{{ 2*ansible_processor_cores }}"   }
        - { r: 'timely', k: 10, b:   0, w: "{{ 2*ansible_processor_cores }}"   }
        - { r: 'timely', k: 12, b:   0, w: "{{ 2*ansible_processor_cores+2 }}" }

    - fetch: src=output dest=data/run-{{ ansible_date_time.iso8601 }}
