---
- hosts: localhost
  tasks:
    - name: "start instance"
      register: ec2
      ec2:
        key_name: ec2
        instance_type: m3.xlarge
        image: ami-fce3c696
        wait: true
        count: 1
        region: us-east-1
        instance_profile_name: S3read
        instance_tags:
          dazone: true
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances


