---
- hosts: localhost
  tasks:
    - name: "start instance"
      register: ec2
      ec2:
        key_name: ec2
        instance_type: c3.8xlarge
        count: 1
  #      placement_group: dazone
  #      instance_type: m3.xlarge
  #      count: 20
        image: ami-fce3c696
        wait: true
        region: us-east-1
        instance_profile_name: S3read
        instance_tags:
          dazone: true

